// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

var NavbarHandle = templ.NewOnceHandle()

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"group absolute top-1/2 flex flex-row\"><div class=\"duration-1200 w-0 overflow-hidden transition-all ease-in-out group-hover:sm:w-20\"><nav hx-boost=\"true\"><ul><li><a class=\"text-green-600\" href=\"/\" hx-swap=\"innerHTML\">Home</a></li><li><a class=\"text-amber-950\" href=\"/career\" hx-swap=\"innerHTML\">Career</a></li></ul></nav></div><div class=\"\"><svg id=\"Expand_Arrow_24\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><rect width=\"24\" height=\"24\" stroke=\"none\" fill=\"#000000\" opacity=\"0\"></rect> <g transform=\"matrix(0.91 0 0 0.91 12 12)\"><path style=\"stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;\" transform=\" translate(-15, -14.99)\" d=\"M 24.990234 8.9863281 C 24.72646293184158 8.99256433006816 24.475842610437518 9.10278123582073 24.292969 9.2929688 L 15 18.585938 L 5.7070312 9.2929688 C 5.518760128868619 9.099436056805526 5.260236101227263 8.9902501391318 4.9902344 8.9902344 C 4.583311403441767 8.990341350615525 4.217025571991593 9.23698988660775 4.063903589598271 9.614004468652404 C 3.9107816072049495 9.991019050697059 4.001357608894798 10.423219002740245 4.2929688 10.707031 L 14.292969 20.707031 C 14.683498808445279 21.097399062146913 15.316501191554721 21.097399062146913 15.707031 20.707031 L 25.707031 10.707031 C 26.00427292868914 10.42120173223119 26.09560250497537 9.982234575940652 25.937028310966724 9.60157021002416 C 25.778454116958073 9.220905844107671 25.40249179423634 8.976599504238846 24.990234 8.9863281 z\" stroke-linecap=\"round\"></path></g></svg></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = NavbarHandle.Once().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
